# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
