# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170919_1243'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
    ]
