# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20170619_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='cover_img',
            field=models.ImageField(blank=True, default='', upload_to=''),
            preserve_default=False,
        ),
    ]
