# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20170919_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='travel_area',
            field=models.CharField(choices=[('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('KR', 'Korea'), ('ASIA', 'Asia'), ('OCE', 'Oceania')], default='', max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='travel_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='travel_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
