# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20170927_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='travel_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='travel_start_date',
            field=models.DateField(null=True),
        ),
    ]
